### ISSUE TITLE
Feature Request: Remove the Nvidia header in the vbios file

### ISSUE THREAD

**Issue by jammsen** [SpaceinvaderOne/Dump_GPU_vBIOS#2]
Hey @SpaceinvaderOne ,
afaik we need to remove via hex the weird Nvidia header to either see a picture or to install drivers (Code 43). Is this planned to have for this script too? Because at the moment the script doesnt seem to have this.

Regards,
Sebastian

**Comment by SpaceinvaderOne** [comment]
A header is only added when you dump a vbios using the techpower ups gpuz programme.   The script dumps the vbios without a header so will work fine for qemu/kvm vms :)
